//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAudioPlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobaStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobaStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualAudioPlayer.GlobaStrings", typeof(GlobaStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The srever is currently offline. Can&apos;t play requested song..
        /// </summary>
        internal static string ServerDown {
            get {
                return ResourceManager.GetString("ServerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server down.
        /// </summary>
        internal static string ServerDownCaption {
            get {
                return ResourceManager.GetString("ServerDownCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop a music folder here:.
        /// </summary>
        internal static string StartHelp0 {
            get {
                return ResourceManager.GetString("StartHelp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply click on the cover image to play the album..
        /// </summary>
        internal static string StartHelp1 {
            get {
                return ResourceManager.GetString("StartHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click again on the cover image to play the next song..
        /// </summary>
        internal static string StartHelp2 {
            get {
                return ResourceManager.GetString("StartHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the SPACE bar to pause music..
        /// </summary>
        internal static string StartHelp3 {
            get {
                return ResourceManager.GetString("StartHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the SPACE bar again to continue playing..
        /// </summary>
        internal static string StartHelp4 {
            get {
                return ResourceManager.GetString("StartHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the right mouse button for additional functions..
        /// </summary>
        internal static string StartHelp5 {
            get {
                return ResourceManager.GetString("StartHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the DELETE key (Del) to delete the selected album..
        /// </summary>
        internal static string StartHelp6 {
            get {
                return ResourceManager.GetString("StartHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use mouse or arrow keys to select album..
        /// </summary>
        internal static string StartHelp7 {
            get {
                return ResourceManager.GetString("StartHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the mouse from outside over the cover image to show the album title..
        /// </summary>
        internal static string StartHelp8 {
            get {
                return ResourceManager.GetString("StartHelp8", resourceCulture);
            }
        }
    }
}
